### ISSUE TITLE
Stop video playing while editing

### ISSUE THREAD

**Issue by BaumGuard** [brarcher/video-transcoder#168] opened 2020-03-28 21:21 UTC
It would be nice if the app had the ability the stop the video playing while editing or is there even a possibility to do that, which I haven't noticed yet?

**Comment by brarcher** [comment] 2020-03-29 06:07
This is likely a duplicate of https://github.com/brarcher/video-transcoder/issues/135

**Closed by brarcher** 2020-03-29 06:07 UTC
Labels: duplicate
